version: '3.8'
services:
  nest-api:
    profiles:
      - api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - nest-postgres
    env_file:
      - .env

  nest-postgres:
    image: postgres:15
    container_name: nest-postgres
    restart: always
    ports:
      - '5454:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis: 
    container_name: cache
    image: redis
    ports: 
      - 6379:6379
    volumes:
      - redis:/data

volumes: 
  redis:
    driver: local
  nest-postgres:
    name: nest-postgres-db
