services:
  postgres:
    image: postgres
    ports:
      - '5454:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis: 
    container_name: cache
    image: redis
    ports: 
      - 6379:6379
    
    volumes:
      - redis:/data

volumes: 
  redis:
    driver: local
